[package]
name = "goms_mini_project1"
version = "0.1.0"
edition = "2021"

[dependencies]
atoi = "2.0.0"
bytes = "1.6.0"
dashmap = "5.5.3"
futures = "0.3.30"
tokio = { version = "1.37.0", features = ["full"] }
